--- Configuration for Warrant Module.
-- @configuration Warrant

--- This table defines the default settings for the Warrant Module.
-- @realm shared
-- @table Configuration
-- @field WarrantedText Indicates whether warrants are removed upon death. | **boolean**
-- @field RemoveWarrantOnDeath Indicates whether warrants are removed upon death. | **boolean**
-- @field WarrantFlag The flag used to denote a warrant. | **string**
-- @field CanSeeWarrants The privilege required to see warrants. | **table**
-- @field CanSeeWarrantsNotifications The privilege required to receive warrant notifications. | **table**
