ITEM.name = "Crystal Device"
ITEM.desc = "TEMPLATE"
ITEM.model = "models/dav0r/thruster.mdl"
ITEM.color = Color(255, 255, 255, 255)
ITEM.material = "models/props_combine/stasisshield_sheet"
ITEM.width = 4
ITEM.uniqueID = ITEM.name
ITEM.height = 4
ITEM.numeral = 45
