ITEM.name = "Crystal Needles"
ITEM.desc = "TEMPLATE"
ITEM.model = "models/weapons/w_bugbait.mdl"
ITEM.color = Color( 255,255,255,255 )
ITEM.material = "false"
ITEM.width = 4
ITEM.uniqueID = ITEM.name
ITEM.height = 4
ITEM.numeral = 46