ITEM.name = "Gold"
ITEM.desc = "A few bars of refined gold ingots, quite hefty and quite valuable."
ITEM.model = "models/zerochain/props_factory/zpf_item_bar.mdl"
ITEM.color = Color( 229,40,255,165 )
ITEM.material = "zerochain/props_factory/items/zpf_metal_gold"
ITEM.width = 1
ITEM.uniqueID = ITEM.name
ITEM.height = 1
ITEM.numeral = 9