ITEM.name = "Iron Ore"
ITEM.desc = "A chunk of rock with bits of iron sprinkled throughout."
ITEM.model = "models/props_junk/rock001a.mdl"
ITEM.color = Color( 201,114,255,87 )
ITEM.material = "zerochain/props_factory/resource/zpf_resource_iron"
ITEM.width = 1
ITEM.uniqueID = ITEM.name
ITEM.height = 1
ITEM.numeral = 1