ITEM.name = "Normal Booster"
ITEM.desc = "TEMPLATE"
ITEM.model = "models/zerochain/props_factory/zpf_rocket.mdl"
ITEM.color = Color(255, 255, 255, 255)
ITEM.material = "false"
ITEM.width = 4
ITEM.uniqueID = ITEM.name
ITEM.height = 4
ITEM.numeral = 68
