ITEM.name = "Oil Stone"
ITEM.desc = "A chunk of rock with oil embedded inside."
ITEM.model = "models/props_junk/rock001a.mdl"
ITEM.color = Color( 45,45,255,45 )
ITEM.material = "zerochain/props_factory/resource/zpf_resource_oil"
ITEM.width = 1
ITEM.uniqueID = ITEM.name
ITEM.height = 1
ITEM.numeral = 3