ITEM.name = "Oil Barrel"
ITEM.desc = "A barrel full of oil. Don't let the Americans know about it."
ITEM.model = "models/zerochain/props_factory/zpf_barrel.mdl"
ITEM.color = Color( 25,25,255,25 )
ITEM.material = "false"
ITEM.width = 3
ITEM.uniqueID = ITEM.name
ITEM.height = 4
ITEM.numeral = 10