ITEM.name = "Research Kit - MK1"
ITEM.desc = "An all-in-one research kit designed to help you learn everything, excluding knowledge we cover in more premium packages."
ITEM.model = "models/zerochain/props_factory/zpf_researchkit.mdl"
ITEM.color = Color(255, 57, 255, 216)
ITEM.material = "false"
ITEM.width = 2
ITEM.uniqueID = ITEM.name
ITEM.height = 2
ITEM.numeral = 38
