ITEM.name = "Small Payload"
ITEM.desc = "TEMPLATE"
ITEM.model = "models/zerochain/props_factory/zpf_rocket_payload01.mdl"
ITEM.color = Color( 255,255,255,255 )
ITEM.material = "false"
ITEM.width = 4
ITEM.uniqueID = ITEM.name
ITEM.height = 4
ITEM.numeral = 65