ITEM.name = "Satellite - MK2"
ITEM.desc = "TEMPLATE"
ITEM.model = "models/zerochain/props_factory/zpf_satelity01.mdl"
ITEM.color = Color(255, 57, 255, 127)
ITEM.material = "false"
ITEM.width = 4
ITEM.uniqueID = ITEM.name
ITEM.height = 4
ITEM.numeral = 29
