ITEM.name = "Uranium"
ITEM.desc = "A chunk of rock with bits of uranium inside. Highly radioactive!"
ITEM.model = "models/props_junk/rock001a.mdl"
ITEM.color = Color(122, 87, 255, 201)
ITEM.material = "zerochain/props_factory/resource/zpf_resource_uranium"
ITEM.width = 1
ITEM.uniqueID = ITEM.name
ITEM.height = 1
ITEM.numeral = 6
