MODULE.name = "Server Whitelist"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "Stock"
MODULE.desc = "Adds a Server Whitelist"
MODULE.identifier = "WhitelistCore"
