net.Receive("OpenDetailedDescriptions", function()
    local ply = net.ReadEntity()
    local descText = net.ReadString()
    local descURL = net.ReadString()
    local frame = vgui.Create("DFrame")
    frame:SetScaledSize(800, 600)
    frame:Center()
    frame:SetTitle(L("detailedDescTitle", ply:Name()))
    frame:MakePopup()
    local leftPanel = vgui.Create("DPanel", frame)
    leftPanel:Dock(LEFT)
    leftPanel:SetWide(400)
    local textEntry = vgui.Create("DTextEntry", leftPanel)
    textEntry:Dock(FILL)
    textEntry:SetMultiline(true)
    textEntry:SetVerticalScrollbarEnabled(true)
    textEntry:SetText(descText)
    local htmlPanel = vgui.Create("DHTML", frame)
    htmlPanel:Dock(FILL)
    if descURL ~= L("openDetDescFallback") then htmlPanel:OpenURL(descURL) end
    frame.OnRemove = function()
        hook.Run("ExtendedDescriptionClosed", ply, descText, descURL)
    end
    hook.Run("ExtendedDescriptionOpened", ply, frame, descText, descURL)
end)

net.Receive("SetDetailedDescriptions", function()
    local steamName = net.ReadString()
    local frame = vgui.Create("DFrame")
    frame:SetScaledSize(800, 600)
    frame:Center()
    frame:SetTitle(L("editDescTitle"))
    frame:MakePopup()
    local textEntry = vgui.Create("DTextEntry", frame)
    textEntry:Dock(FILL)
    textEntry:SetMultiline(true)
    textEntry:SetVerticalScrollbarEnabled(true)
    local prevDesc = LocalPlayer():getChar():getData("textDetDescData")
    if prevDesc then textEntry:SetText(prevDesc) end
    local urlEntry = vgui.Create("DTextEntry", frame)
    urlEntry:Dock(BOTTOM)
    urlEntry:SetTall(30)
    local prevURL = LocalPlayer():getChar():getData("textDetDescDataURL")
    if prevURL then
        urlEntry:SetText(prevURL)
    else
        urlEntry:SetText(L("refImagePlaceholder"))
    end

    local button = vgui.Create("liaSmallButton", frame)
    button:Dock(BOTTOM)
    button:SetText(L("edit"))
    button.DoClick = function()
        net.Start("EditDetailedDescriptions")
        net.WriteString(urlEntry:GetValue())
        net.WriteString(textEntry:GetValue())
        net.WriteString(steamName)
        net.SendToServer()
        hook.Run("ExtendedDescriptionEditSubmitted", steamName, urlEntry:GetValue(), textEntry:GetValue())
        frame:Close()
    end
    frame.OnRemove = function()
        hook.Run("ExtendedDescriptionEditClosed", steamName)
    end
    hook.Run("ExtendedDescriptionEditOpened", frame, steamName)
end)
