--- Configuration for Free Look Module.
-- @configuration FreeLook

--- This table defines the default settings for the Free Look Module.
-- @realm shared
-- @table Configuration
-- @field FreelookLimV Specifies the limit of vertical movement of the camera | **number**
-- @field FreelookLimH Specifies the limit of horizontal movement of the camera | **number**
-- @field FreelookSmooth Specifies the smoothness of camera turns | **number**
-- @field FreelookBlockADS Specifies whether the camera should return to the default position when pressing LMB (left mouse button) | **boolean**
-- @field FreelookEnabled Specifies whether freelook mode is enabled | **boolean**