net.Receive("WarnReasonUI", function()
    local tCharID = net.ReadInt(32)
    local frame = vgui.Create("DFrame")
    frame:SetSize(300, 150)
    frame:SetTitle(L("warnReasonTitle"))
    frame:Center()
    frame:MakePopup()
    local textEntry = vgui.Create("DTextEntry", frame)
    textEntry:SetPos(10, 30)
    textEntry:SetSize(280, 20)
    local submitButton = vgui.Create("DButton", frame)
    submitButton:SetPos(10, 70)
    submitButton:SetSize(280, 30)
    submitButton:SetText(L("submit"))
    submitButton.DoClick = function()
        local reason = textEntry:GetValue()
        reason = reason ~= "" and reason or L("notSpecified")
        net.Start("ApplyWarn")
        net.WriteInt(tCharID, 32)
        net.WriteString(reason)
        net.SendToServer()
        frame:Close()
    end
end)
