ITEM.name = "Blue Chip"
ITEM.desc = "TEMPLATE"
ITEM.model = "models/zerochain/props_factory/zpf_chip.mdl"
ITEM.color = Color( 130,217,255,184 )
ITEM.material = "false"
ITEM.width = 4
ITEM.uniqueID = ITEM.name
ITEM.height = 4
ITEM.numeral = 23