ITEM.name = "Copper Wire"
ITEM.desc = "A roll of copper wire ready for all of your electrical needs."
ITEM.model = "models/zerochain/props_factory/zpf_wireroll.mdl"
ITEM.color = Color( 188,55,255,102 )
ITEM.material = "false"
ITEM.width = 1
ITEM.uniqueID = ITEM.name
ITEM.height = 1
ITEM.numeral = 18