MODULE.name = "Animations"
MODULE.author = "Samael"
MODULE.discord = "@liliaplayer"
MODULE.desc = "Adds extra animation support for characters and items."
MODULE.version = "1.0"
MODULE.versionID = "public_animations"
