--- Configuration for the F1 Menu Expansions Module.
-- @configuration F1MenuExpansion

--- This table defines the default settings for the F1 Menu Expansions Module.
-- @realm shared
-- @table Configuration
-- @field RulesEnabled Should DownTime be Enabled | **bool**
-- @field TutorialEnabled Should DownTime be Enabled | **bool**
-- @field FAQEnabled Should DownTime be Enabled | **bool**
-- @field FAQQuestions Frequently Asked Questions | **table**
-- @field RulesConfig Rules configuration for the server | **table**