MODULE.name = "Development Server"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "Stock"
MODULE.desc = "Adds the option for a Development Server, which can run specific functions."
