--- Configuration for AFK Manager Module.
-- @configuration AFKManager

--- This table defines the default settings for the AFK Manager Module.
-- @realm shared
-- @table Configuration
-- @field WarningTime Specifies the time in seconds before issuing an AFK warning | **number**
-- @field TimerInterval Specifies the interval in seconds for checking AFK status | **number**
-- @field KickTime Specifies the time in seconds before kicking an AFK player | **number**
-- @field AFKAllowedPlayers Specifies a list of players allowed to be AFK without consequences | **table**
-- @field KickMessage Specifies the message sent to AFK players before they are kicked | **string**
-- @field WarningHead Specifies the header of the AFK warning message | **string**
-- @field WarningSub Specifies the subtext of the AFK warning message | **string**