gh-pages:
  runs-on: ubuntu-latest
  needs: scrape-modules
  steps:
    - name: Checkout Code from Main Branch
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0

    - name: Download Module ZIPs
      uses: actions/download-artifact@v4
      with:
        name: module-zips
        path: downloaded_zips

    - name: Extract Module ZIPs
      run: |
        for zip in downloaded_zips/*.zip; do
          # Extract each ZIP into its own folder named after the ZIP file (without extension)
          folder="extracted_$(basename "$zip" .zip)"
          mkdir -p "$folder"
          unzip "$zip" -d "$folder"
        done

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Debug Downloaded
      run: |
        echo "Zips in downloaded_zips:"
        ls -lah downloaded_zips || echo "No zips found"
        echo "Extracted directories:"
        ls -d extracted_* || echo "No extracted folders found"

    - name: Generate Site
      run: node docs/docsparser.js

    - name: Debug Docs
      run: |
        echo "Final docs folder structure before deploying:"
        ls -R docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.LiliaGitSecret }}
        publish_branch: gh-pages
        publish_dir: ./docs
        force_orphan: true