name: CI
on:
  push:
    branches:
      - main
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: modules
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: 5.2
      - uses: leafo/gh-actions-luarocks@v4.0.0
      - uses: actions/checkout@v3
        with:
          repository: LiliaFramework/GluaCheck
          path: luacheck
      - run: luarocks make
        working-directory: luacheck
      - run: |
          luacheck . \
            --no-redefined \
            --no-global --no-self \
            --no-max-line-length --no-max-code-line-length \
            --no-max-string-line-length --no-max-comment-line-length
        working-directory: modules
  scrape-modules:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - run: sudo apt-get update && sudo apt-get install -y jq zip
      - run: |
          echo "[]" > modules_data.json
          for module in */module.lua; do
            [ -f "$module" ] || continue
            name=$(grep -Po 'MODULE\.name\s*=\s*"[^"]*"' "$module" | sed -E 's/.*=\s*"([^"]+)".*/\1/')
            author=$(grep -Po 'MODULE\.author\s*=\s*"[^"]*"' "$module" | sed -E 's/.*=\s*"([^"]+)".*/\1/')
            discord=$(grep -Po 'MODULE\.discord\s*=\s*"[^"]*"' "$module" | sed -E 's/.*=\s*"([^"]+)".*/\1/')
            desc=$(grep -Po 'MODULE\.desc\s*=\s*"[^"]*"' "$module" | sed -E 's/.*=\s*"([^"]+)".*/\1/')
            version=$(grep -Po 'MODULE\.version\s*=\s*"[^"]*"' "$module" | sed -E 's/.*=\s*"([^"]+)".*/\1/' || echo "1.0")
            raw_features=$(grep -Po 'MODULE\.Features\s*=\s*(\{[^}]*\}|"[^"]*")' "$module" | head -n1 | sed -E 's/MODULE\.Features\s*=\s*//')
            if [ -n "$raw_features" ]; then
              if [[ $raw_features == \{* ]]; then
                raw_features=$(echo "$raw_features" | sed -E 's/,\s*}$/}/')
                features_line=$(echo "$raw_features" | sed -E 's/^\{(.*)\}$/[\1]/')
              else
                features_line="[$raw_features]"
              fi
            else
              features_line="[]"
            fi
            raw_workshop=$(grep -Po 'MODULE\.WorkshopContent\s*=\s*(\{[^}]*\}|"[^"]*")' "$module" | head -n1 | sed -E 's/MODULE\.WorkshopContent\s*=\s*//')
            if [ -n "$raw_workshop" ]; then
              if [[ $raw_workshop == \{* ]]; then
                raw_workshop=$(echo "$raw_workshop" | sed -E 's/,\s*}$/}/')
                workshop_line=$(echo "$raw_workshop" | sed -E 's/^\{(.*)\}$/[\1]/')
              else
                workshop_line="[$raw_workshop]"
              fi
            else
              workshop_line="[]"
            fi
            folder=$(basename "$(dirname "$module")")
            public_uniqueID=$folder
            download="https://github.com/LiliaFramework/Modules/raw/refs/heads/gh-pages/Downloads/${folder}.zip"
            source="https://liliaframework.github.io/Modules/${folder}.html"
            jq --arg name "$name" \
               --arg author "$author" \
               --arg discord "$discord" \
               --arg desc "$desc" \
               --arg version "$version" \
               --arg download "$download" \
               --arg source "$source" \
               --arg public_uniqueID "$public_uniqueID" \
               --argjson features "$features_line" \
               --argjson workshop "$workshop_line" \
               '. += [{name:$name,author:$author,discord:$discord,description:$desc,version:$version,download:$download,source:$source,public_uniqueID:$public_uniqueID,features:$features,workshop:$workshop}]' modules_data.json > tmp.json
            mv tmp.json modules_data.json
          done
      - run: |
          for folder in */; do
            [ -d "$folder" ] && zip -r "${folder%/}.zip" "$folder"
          done
      - run: node scrap_modules.js
      - run: |
          git clone https://x-access-token:${{ secrets.LiliaGitSecret }}@github.com/LiliaFramework/Lilia.git lilia
          mkdir -p lilia/documentation
          cp documentation/modules.md lilia/documentation/modules.md
          cd lilia
          git config user.email "githubactions@github.com"
          git config user.name "GitHub Actions"
          git add documentation/modules.md
          if ! git diff --cached --quiet; then
            git commit -m "Update modules summary"
            git push https://x-access-token:${{ secrets.LiliaGitSecret }}@github.com/LiliaFramework/Lilia.git HEAD:main
          fi
      - run: mv modules_data.json modules.json
      - run: |
          git clone https://x-access-token:${{ secrets.LiliaGitSecret }}@github.com/LiliaFramework/LiliaFramework.github.io.git website
          cp modules.json website/modules.json
          cd website
          git config user.email "githubactions@github.com"
          git config user.name "GitHub Actions"
          git add modules.json
          if ! git diff --cached --quiet; then
            git commit -m "Update modules.json with source URLs"
            git push https://x-access-token:${{ secrets.LiliaGitSecret }}@github.com/LiliaFramework/LiliaFramework.github.io.git HEAD:main
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: module-zips
          path: ./*.zip
      - uses: actions/upload-artifact@v4
        with:
          name: modules-json
          path: modules.json
  gh-pages:
    needs: scrape-modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: mkdir -p documentation
      - uses: actions/download-artifact@v4
        with:
          name: module-zips
          path: documentation/Downloads
      - uses: actions/download-artifact@v4
        with:
          name: modules-json
          path: documentation
      - run: |
          for zip in documentation/Downloads/*.zip; do
            folder=$(basename "$zip" .zip)
            unzip "$zip" -d "extracted_${folder}"
          done
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.LiliaGitSecret }}
          publish_branch: gh-pages
          publish_dir: documentation
          force_orphan: true
      - uses: actions/upload-artifact@v4
        with:
          name: built-docs
          path: documentation
  upload-docs:
    needs: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: built-docs
          path: built-docs
      - uses: actions/checkout@v3
        with:
          repository: LiliaFramework/Lilia
          token: ${{ secrets.LiliaGitSecret }}
          path: lilia
          fetch-depth: 0
      - run: |
          mkdir -p lilia/documentation/docs
          cp -R built-docs/. lilia/documentation/docs
      - run: |
          cd lilia
          git config user.email "githubactions@github.com"
          git config user.name "GitHub Actions"
          git add documentation/docs
          if ! git diff --cached --quiet; then
            git commit -m "Update Module Documentation"
            git push https://x-access-token:${{ secrets.LiliaGitSecret }}@github.com/LiliaFramework/Lilia.git HEAD:main
          fi
