ENT.Type = "anim"
ENT.PrintName = "Slot Machine"
ENT.Author = "Samael"
ENT.Category = "Lilia"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.AdminOnly = true
ENT.IsPersistent = true
ENT.NoPhysgun = true
ENT.NoRemover = true
ENT.IsPersistent = true